### ISSUE TITLE
No LXC rpms for EPEL8 / Centos8

### ISSUE THREAD

**Issue by f18m** [ganto/copr-lxc#2]
Hi,
since I'm having troubles to use LXC3 on Centos 8 (I filed this bug: https://github.com/lxc/lxc-templates/issues/21) I would like to try out using LXC2 but I noticed that this project does not build for EPEL8 / Centos8... is it possible to add EPEL8 / Centos8 builds? thanks!

**Comment by ganto** [comment]
I don't think it makes any difference, as the lxc-templates from LXC2 are actually the same but bundled with LXC instead of separately. With LXC3 and especially LXD the traditional shell templates were deprecated in favour of [lxc/distrobuilder](https://github.com/lxc/distrobuilder). It just recently got [support for CentOS 8](https://github.com/lxc/lxc-ci/issues/83).

Now you have the following options:
- Adjust the traditional [lxc-centos](https://github.com/lxc/lxc-templates/blob/master/templates/lxc-centos.in) shell script template to deal with CentOS 8. That might be quite a lot of work...
- Use the pre-built container image from [images.linuxcontainers.org](https://images.linuxcontainers.org/) via LXC download template:
```
lxc-create -t download --name test01 -- --dist centos --release 8 --arch amd64
```
- Or you build your own CentOS 8 image with distrobuilder. If I find time I will try to update the distrobuilder RPM in the [copr-lxc3](https://copr.fedorainfracloud.org/coprs/ganto/lxc3/) repository in the coming days. The version currently packaged is a bit outdated and doesn't support CentOS 8 yet. Otherwise you can build distrobuilder yourself with the installation instructions from the [README](https://github.com/lxc/distrobuilder/blob/master/doc/index.md)

**Comment by f18m** [comment]
Hi @ganto ,
Thanks for the detailed answer.
I just tried out the "lxc-create -t download" method and I was able to successfully create a centos8 LXC container, thank you very much!

I just wonder why in case you give "-t centos" they don't print any warning to inform you about this deprecation :)

Thanks!
